Description: |
    Amazon Cognito User Pool and User Pool Client deployment for Edge Authentication stack
    You will be billed for the AWS resources used if you create a stack from this template. **NOTICE** Copyright 2018 Alma Media Oyj or its affiliates.
    All Rights Reserved. Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License. A copy of the License is located at
    http://www.apache.org/licenses/LICENSE-2.0 or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and limitations under the License.
Parameters:
  ArtifactBucket:
    Description: S3 bucket with artifact files (Cloudformation templates)
    Type: String
    Default: cloudfront-blog-resources
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-.]*[0-9a-zA-Z])*$
    ConstraintDescription: ArtifactsBucket S3 bucket name can include numbers, lowercase letters, uppercase letters, periods (.) and hyphens (-). It cannot start or end with a hyphen (-).
  ArtifactPrefix:
    Description: Path in the S3 bucket containing artifact files
    Type: String
    Default: authorization-lambda-at-edge/
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: ArtifactPrefix key prefix can include numbers, lowercase letters, uppercase letters, periods (.) hyphens (-), and forward slash (/).
  CallbackUrls:
    Description: comma-separated list of URLs that are valid callback URLS for cognito signin and signout operations, ie. where to return user after sign in or out. You can update this list later, just put something here.
    Type: String
Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
                - lambda.amazonaws.com
          Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
                - logs:*
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
                - cognito-idp:List*
                - cognito-idp:Get*
                - cognito-idp:Describe*
                - cognito-idp:CreateUserPool
                - cognito-idp:CreateUserPoolClient
                - cognito-idp:CreateUserPoolDomain
                - cognito-idp:DeleteUserPool
                - cognito-idp:DeleteUserPoolClient
                - cognito-idp:DeleteUserPoolDomain
            Resource: 
                - '*'

  UserPoolAndClientResourceLambda: 
    Type: AWS::Lambda::Function
    Properties: 
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.6
      Timeout: 60
      Code: 
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Sub ${ArtifactPrefix}/userpool.zip

  UserPoolAndClient:
    Type: Custom::CreateUserPoolAndClient
    Properties:
      ServiceToken: !GetAtt UserPoolAndClientResourceLambda.Arn
      CallbackUrls: !Ref CallbackUrls

Outputs:
  UserPoolId:
    Description: generated ID for this UserPool
    Value: !GetAtt UserPoolAndClient.UserPoolId
  UserPoolClientId:
    Description: generated ID for this UserPoolClient
    Value: !GetAtt UserPoolAndClient.ClientId
