Description: |
    Cloudformation Edge Authentication with Cognito and Lambda@Edge.
    You will be billed for the AWS resources used if you create a stack from this template. **NOTICE** Copyright 2017 Amazon.com, Inc. or its affiliates.
    All Rights Reserved. Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License. A copy of the License is located at
    http://www.apache.org/licenses/LICENSE-2.0 or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and limitations under the License.

Parameters:
  CallbackUrls:
    Description: comma-separated list of URLs that are valid callback URLS for cognito signin and signout operations, ie. where to return user after sign in or out. You can update this list later, just put something here.
    Type: String
  ArtifactBucket:
    Description: S3 bucket with artifact files (Cloudformation templates)
    Type: String
    Default: cloudfront-blog-resources
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-.]*[0-9a-zA-Z])*$
    ConstraintDescription: ArtifactsBucket S3 bucket name can include numbers, lowercase letters, uppercase letters, periods (.) and hyphens (-). It cannot start or end with a hyphen (-).
  ArtifactBucketUs:
    Description: S3 bucket with artifact files in us-east-1 (Lambda functions)
    Type: String
    Default: cloudfront-blog-resources
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-.]*[0-9a-zA-Z])*$
    ConstraintDescription: ArtifactsBucket S3 bucket name can include numbers, lowercase letters, uppercase letters, periods (.) and hyphens (-). It cannot start or end with a hyphen (-).
  ArtifactPrefix:
    Description: Path in the S3 bucket containing artifact files
    Type: String
    Default: authorization-lambda-at-edge/
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: ArtifactPrefix key prefix can include numbers, lowercase letters, uppercase letters, periods (.) hyphens (-), and forward slash (/).

Resources:
  CognitoUserPool:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactBucket}/${ArtifactPrefix}/cognito-user-pool.yaml
      Parameters:
        CallbackUrls: !Ref CallbackUrls
        ArtifactBucket:   !Ref ArtifactBucket
        ArtifactPrefix:   !Ref ArtifactPrefix

  LambdaAtEdge:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:    !Sub https://s3.amazonaws.com/${ArtifactBucket}/${ArtifactPrefix}/lambda-at-edge.yaml
      Parameters:
        UserPoolId:     !GetAtt CognitoUserPool.Outputs.UserPoolId
        UserPoolClientId:     !GetAtt CognitoUserPool.Outputs.UserPoolClientId
        ArtifactBucket:   !Ref ArtifactBucketUs
        ArtifactPrefix:   !Ref ArtifactPrefix

Outputs:
  CognitoUserPoolId: 
    Value: !GetAtt CognitoUserPool.Outputs.UserPoolId
    Export:
      Name: il-auth-at-edge-userpool-id
  CognitoUserPoolClientId: 
    Value: !GetAtt CognitoUserPool.Outputs.UserPoolClientId
    Export:
      Name: il-auth-at-edge-userpool-client-id
  CognitoUserPool:
    Description: User pool contains user credentials.  For cleanup, delete Domain Name first, then delete the user pool.
    Value: !Sub https://console.aws.amazon.com/cognito/users/?region=${AWS::Region}#/pool/${CognitoUserPool.Outputs.UserPoolId}
    Export: 
      Name: il-auth-at-edge-userpool
  LambdaAtEdgeFunction:
    Description: Edit Lambda at Edge and publish
    Value: !Sub 'https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions/${LambdaAtEdge.Outputs.EdgeAuthFunction}'
    Export: 
      Name: il-auth-at-edge-lambda-function
  LambdaAtEdgeFunctionVersionARN:
    Description: Arn for the published version of edge auth function
    Value: !GetAtt LambdaAtEdge.Outputs.EdgeAuthFunctionInitialVersion
    Export: 
      Name: il-auth-at-edge-lambda-function-version-arn
