Description: |
    Lambda at edge function and a custom resource that configures the function
    You will be billed for the AWS resources used if you create a stack from this template. **NOTICE** Copyright 2018 Alma Media Oyj or its affiliates.
    All Rights Reserved. Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License. A copy of the License is located at
    http://www.apache.org/licenses/LICENSE-2.0 or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and limitations under the License.

Parameters:

  UserPoolId:
    Type: String
  UserPoolClientId:
    Type: String
  ArtifactBucket:
    Type: String
  ArtifactBucketUS:
    Type: String
  ArtifactPrefix:
    Type: String
  LambdaZipRevisionSuffix:
    Description: Suffix added to lambda function code zipfile name to ensure code change is registered
    Type: String

Resources:
  UpdateConfigExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - s3:*
            Resource: 
            - !Sub 'arn:aws:s3:::${ArtifactBucketUS}/*'
            - !Sub 'arn:aws:s3:::${ArtifactBucketUS}'

  UpdateConfigFunction: 
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: il-auth-at-edge-UpdateConfig
      Handler: index.handler
      Role: !GetAtt UpdateConfigExecutionRole.Arn
      Runtime: python3.6
      Timeout: 60
      MemorySize: 1536
      Code: 
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Sub ${ArtifactPrefix}/updateconfig-${LambdaZipRevisionSuffix}.zip

  UpdateConfig:
    Type: Custom::UpdateConfig
    DeletionPolicy: Retain
    Properties:
      ServiceToken: !GetAtt UpdateConfigFunction.Arn
      ArtifactBucket: !Ref ArtifactBucketUS
      ArtifactPrefix: !Ref ArtifactPrefix
      AWSRegion: !Ref "AWS::Region"
      UserPoolId: !Ref UserPoolId
      ZipFile: !Sub edge-auth-${LambdaZipRevisionSuffix}.zip
      UserPoolClientId: !Ref UserPoolClientId

  CreateLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
              - lambda:*
            Resource: 
              - !Sub arn:aws:lambda:us-east-1:${AWS::AccountId}:*
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: '*'
          - Effect: Allow
            Action:
            - s3:*
            Resource: 
            - !Sub 'arn:aws:s3:::${ArtifactBucketUS}/*'
            - !Sub 'arn:aws:s3:::${ArtifactBucketUS}'

  CreateLambdaFunction: 
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: il-auth-at-edge-CreateLambda
      Handler: index.handler
      Role: !GetAtt CreateLambdaExecutionRole.Arn
      Runtime: python3.6
      Timeout: 60
      MemorySize: 1536
      Code: 
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Sub ${ArtifactPrefix}/createlambda-${LambdaZipRevisionSuffix}.zip

  EdgeAuthExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
        - Effect: Allow
          Principal:
            Service:
            - edgelambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: !Sub arn:aws:logs:us-east-1:${AWS::AccountId}:*

  EdgeAuth: 
    Type: Custom::CreateLambdaFunctionOnSpecifiedRegion
    DependsOn: UpdateConfig
    DeletionPolicy: Retain
    Properties:
      ServiceToken: !GetAtt CreateLambdaFunction.Arn
      Handler: index.handler
      FunctionName: !Sub il-auth-at-edge-EdgeAuth
      Runtime: nodejs8.10
      Timeout: 1
      MemorySize: 128
      Role: !GetAtt EdgeAuthExecutionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucketUS
        S3Key: !Sub ${ArtifactPrefix}/edge-auth-${LambdaZipRevisionSuffix}.zip
      AWSRegion: us-east-1

Outputs:
  EdgeAuthFunction: 
    Description: Reference to the Lambda function
    Value: !GetAtt EdgeAuth.Arn
  EdgeAuthFunctionInitialVersion: 
    Description: Reference to the Lambda function published version
    Value: !Join
      - ':'
      - - !GetAtt EdgeAuth.Arn
        - !GetAtt EdgeAuth.Version




