Description: |
    Amazon Cognito User Pool and User Pool Client deployment for Edge Authentication sample stack
    You will be billed for the AWS resources used if you create a stack from this template. **NOTICE** Copyright 2018 Alma Media Oyj or its affiliates.
    All Rights Reserved. Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License. A copy of the License is located at
    http://www.apache.org/licenses/LICENSE-2.0 or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and limitations under the License.

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig: 
        AllowAdminCreateUserOnly: true
        UnusedAccountValidityDays: 7
      AliasAttributes: 
        - email
      AutoVerifiedAttributes: 
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: true
      Schema: 
        - Name: email
          Required: true
        - Name: name
          Required: true
        - Name: family_name
          Required: true
      UserPoolName: il-auth-at-edge-userpool
  
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: il-auth-at-edge-userpool-client
      GenerateSecret: true
      ReadAttributes: 
        - email
        - email_verified
        - family_name
        - name
        - preferred_username
        - profile
        - updated_at
        - website
        - zoneinfo
      RefreshTokenValidity: 7
      UserPoolId: !Ref UserPool
      WriteAttributes: 
        - email
        - family_name
        - name
        - preferred_username
        - profile
        - updated_at
        - website
        - zoneinfo

Outputs:
  UserPoolId:
    Description: generated ID for this UserPool
    Value: !Ref UserPool
  UserPoolClientId:
    Description: generated ID for this UserPoolClient
    Value: !Ref UserPoolClient
